FROM tensorflow/tensorflow:latest-gpu-jupyter

EXPOSE 8888

# Aggiungere i pacchetti desiderati
RUN pip install pandas pydot graphviz scikit-learn pydot catppuccin-jupyterlab
RUN apt update
RUN apt install wget graphviz python3-tk -y
