FROM tensorflow/tensorflow:latest-jupyter

EXPOSE 8888

# Aggiungere i pacchetti desiderati
RUN apt update
RUN apt install wget graphviz python3-tk -y
RUN pip install pandas pydot graphviz scikit-learn pydot catppuccin-jupyterlab opencv-python
